# Generated by Django 4.2.5 on 2023-09-24 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CreateAccount', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='UserName',
            new_name='username',
        ),
    ]
