# Generated by Django 4.2.5 on 2023-09-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateAccount', '0002_rename_username_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='senha',
            field=models.CharField(max_length=500),
        ),
    ]
