# Generated by Django 4.2.5 on 2023-09-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamenome', models.CharField(max_length=50)),
                ('descricao', models.EmailField(max_length=500)),
                ('nota', models.IntegerField()),
                ('categoria', models.CharField(max_length=20)),
                ('foto', models.ImageField(upload_to='fotos/')),
            ],
        ),
    ]
