# Generated by Django 4.2.5 on 2023-10-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='descricao',
            field=models.CharField(max_length=10000),
        ),
    ]
